openapi: 3.0.0
info:
  title: Trade Parsing and Balance Calculator
  version: "1.0"
  description: "A simple server side application using Node.js and MongoDB which parses data from 
                CSV and stores it in Database and further used to calculate balance."
servers:
  - url: "https://trade-parsing-and-balance-calculator.onrender.com/"
paths:
  /api/trade/upload:
    post:
      summary: Upload CSV
      description: This is the API endpoint to upload a CSV file and store the data in the database.
      tags:
        - Trade
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csvFile:
                  type: string
                  format: binary
                  description: The CSV file to upload
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Inserted successfully"
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error inserting data"
                  error:
                    type: object

  /api/user/check-balance:
    post:
      summary: Get Balance
      description: This is the API endpoint to get the asset-wise balance of the account at any given timestamp.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
                  format: date-time
                  example: "2022-09-28 12:00:00"
                  description: The timestamp to get the balance at
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: number
                  example: 100
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error fetching balance"
                  error:
                    type: object